// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rnecujbcamhpxuyrysxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZWN1amJjYW1ocHh1eXJ5c3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODg4OTgsImV4cCI6MjA3NzA2NDg5OH0.yk80cMijaCV2uwr0w3B49bvmMKWTioX3Q4GeiW-Flqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);